import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // you can customize weights
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${workSans.className} antialiased px-[312px]`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
