export const carList = [
  {
    name: "Mercedes",
    type: "Sedan",
    price: 25,
    fuel: "Petrol",
    seats: 5,
    doors: 4,
    distance: "12k km",
    image: "/carImage/car1.svg",
  },
  {
    name: "BMW",
    type: "Cabriolet",
    price: 55,
    fuel: "Diesel",
    seats: 4,
    doors: 2,
    distance: "8k km",
    image: "/carImage/car2.svg",
  },
  {
    name: "Ford",
    type: "Pickup",
    price: 45,
    fuel: "Gas",
    seats: 2,
    doors: 2,
    distance: "18k km",
    image: "/carImage/car3.svg",
  },
  {
    name: "Porsche",
    type: "SUV",
    price: 50,
    fuel: "Petrol",
    seats: 5,
    doors: 4,
    distance: "22k km",
    image: "/carImage/car4.svg",
  },
  {
    name: "Toyota",
    type: "Minivan",
    price: 40,
    fuel: "Diesel",
    seats: 7,
    doors: 5,
    distance: "35k km",
    image: "/carImage/car5.svg",
  },
  {
    name: "Tesla",
    type: "Sedan",
    price: 65,
    fuel: "Electric",
    seats: 5,
    doors: 4,
    distance: "6k km",
    image: "/carImage/car6.svg",
  },
  {
    name: "Audi",
    type: "Cabriolet",
    price: 70,
    fuel: "Petrol",
    seats: 4,
    doors: 2,
    distance: "10k km",
    image: "/carImage/car7.svg",
  },
  {
    name: "Kia",
    type: "SUV",
    price: 35,
    fuel: "Diesel",
    seats: 5,
    doors: 4,
    distance: "28k km",
    image: "/carImage/car8.svg",
  },
  {
    name: "Maybach",
    type: "Sedan",
    price: 80,
    fuel: "Petrol",
    seats: 5,
    doors: 4,
    distance: "14k km",
    image: "/carImage/car9.svg",
  },
];
